### ISSUE TITLE
Error with -std=c++11

### ISSUE THREAD

**Issue by SethuGitHub** [HermannHesse/faster_rcnn_cplusplus#2] opened 2017-05-22 11:19 UTC
**I got the below error with -std=c++11**

usr/include/c++/4.8/bits/stl_algo.h: In instantiation of ‘_RandomAccessIterator std::__unguarded_partition(_RandomAccessIterator, _RandomAccessIterator, const _Tp&) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<Info*, std::vector<Info> >; _Tp = Info]’:
/usr/include/c++/4.8/bits/stl_algo.h:2283:70:   required from ‘_RandomAccessIterator std::__unguarded_partition_pivot(_RandomAccessIterator, _RandomAccessIterator) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<Info*, std::vector<Info> >]’
/usr/include/c++/4.8/bits/stl_algo.h:2315:54:   required from ‘void std::__introsort_loop(_RandomAccessIterator, _RandomAccessIterator, _Size) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<Info*, std::vector<Info> >; _Size = long int]’
/usr/include/c++/4.8/bits/stl_algo.h:5461:36:   required from ‘void std::sort(_RAIter, _RAIter) [with _RAIter = __gnu_cxx::__normal_iterator<Info*, std::vector<Info> >]’
/home/faster_rcnn_cplusplus/faster_rcnn.cpp:262:35:   required from here
/usr/include/c++/4.8/bits/stl_algo.h:2245:19: error: passing ‘const Info’ as ‘this’ argument of ‘bool Info::operator<(const Info&)’ discards qualifiers [-fpermissive]
    while (__pivot < *__last)
                   ^
make[2]: *** [CMakeFiles/faster_rcnn_cplusplus.dir/faster_rcnn.cpp.o] Error 1
make[1]: *** [CMakeFiles/faster_rcnn_cplusplus.dir/all] Error 2
make: *** [all] Error 2

**when i tried with -std=c++0x in  CMakeLists.txt, i got below errors.**

/usr/include/c++/4.8/cmath(337): error: expected a ";"

/usr/include/c++/4.8/cmath(356): error: inline specifier allowed on function declarations only

/usr/include/c++/4.8/cmath(356): error: variable "std::constexpr" has already been defined

/usr/include/c++/4.8/cmath(356): error: expected a ";"

/usr/include/c++/4.8/cmath(375): error: inline specifier allowed on function declarations only

/usr/include/c++/4.8/cmath(375): error: variable "std::constexpr" has already been defined

/usr/include/c++/4.8/cmath(375): error: expected a ";"

/usr/include/c++/4.8/cmath(406): error: inline specifier allowed on function declarations only

/usr/include/c++/4.8/cmath(406): error: variable "std::constexpr" has already been defined

/usr/include/c++/4.8/cmath(406): error: expected a ";"

/usr/include/c++/4.8/cmath(443): error: inline specifier allowed on function declarations only

/usr/include/c++/4.8/cmath(443): error: variable "std::constexpr" has already been defined

/usr/include/c++/4.8/cmath(443): error: expected a ";"

Error limit reached.
100 errors detected in the compilation of "/tmp/tmpxft_00010fe0_00000000-7_nms_kernel.cpp1.ii".
Compilation terminated.
CMake Error at faster_rcnn_cplusplus_generated_nms_kernel.cu.o.cmake:282 (message):
  Error generating file
  /home/faster_rcnn_cplusplus/build/CMakeFiles/faster_rcnn_cplusplus.dir/py-faster-rcnn/lib/nms/./faster_rcnn_cplusplus_generated_nms_kernel.cu.o

make[2]: *** [CMakeFiles/faster_rcnn_cplusplus.dir/py-faster-rcnn/lib/nms/faster_rcnn_cplusplus_generated_nms_kernel.cu.o] Error 1
make[1]: *** [CMakeFiles/faster_rcnn_cplusplus.dir/all] Error 2
make: *** [all] Error 2

**Any help, suggestion or followup would be highly appreciated**

**Comment by HermannHesse** [comment] 2017-05-23 17:28
I'm sorry, but I can't currently test the code with the compiler version that you are using (`GCC 4.8`). You have to execute them with `-std=c++11` flag, that's for sure.

As I can see in the first error, the problem is in the sort function implemented within the [`struct Info`](https://github.com/HermannHesse/faster_rcnn_cplusplus/blob/9625d39eeaedd7af2359107b1373a9554e9d290f/faster_rcnn.hpp#L49-L51) called in [`std::sort(my.begin(), my.end())`](https://github.com/HermannHesse/faster_rcnn_cplusplus/blob/9625d39eeaedd7af2359107b1373a9554e9d290f/faster_rcnn.cpp#L262).

Reading similar errors, in `GCC 4.8` version the arguments in sort predicate must have `const` specifiers. It was probably fixed in `GCC 4.9.0+`, and it is the easiest way to run it correctly. As soon as possible I will fix the code for the `GCC 4.8` version. Thanks for reporting.

Regards.

**Closed as completed** 2020-01-03 10:54 UTC
